repos:
  - repo: local
    hooks:
      - id: black
        name: black
        stages: [commit]
        language: system
        types: [python]
        entry: pipenv run black --force-exclude

      - id: isort
        name: isort
        stages: [commit]
        language: system
        types: [python]
        # run for each file in the commit, respects skip/skip_glob filters if present in config file .isort.cfg
        entry: pipenv run isort --filter-files