# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=255)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('height', models.BigIntegerField(blank=True, null=True)),
                ('version', models.BigIntegerField(blank=True, null=True)),
                ('merkle_root', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('nonce', models.BigIntegerField(blank=True, null=True)),
                ('bits', models.CharField(blank=True, max_length=255, null=True)),
                ('difficulty', models.FloatField(blank=True, null=True)),
                ('mint', models.FloatField(blank=True, null=True)),
                ('previous_block_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('next_block_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('flags', models.CharField(blank=True, max_length=255, null=True)),
                ('proof_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('entropy_bit', models.BigIntegerField(blank=True, null=True)),
                ('modifier', models.CharField(blank=True, max_length=255, null=True)),
                ('modifier_checksum', models.CharField(blank=True, max_length=255, null=True)),
                ('coinage_destroyed', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustodianVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FeesVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MotionVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ParkRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ParkRateVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(max_length=255)),
                ('version', models.IntegerField()),
                ('lock_time', models.IntegerField(blank=True, null=True)),
                ('is_coin_base', models.BooleanField()),
                ('is_coin_stake', models.BooleanField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', related_query_name='transaction', to='blocks.Block')),
            ],
        ),
        migrations.CreateModel(
            name='TxInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(blank=True, max_length=255, null=True)),
                ('v_out', models.BigIntegerField(blank=True, null=True)),
                ('coin_base', models.CharField(blank=True, max_length=255, null=True)),
                ('sequence', models.BigIntegerField(blank=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tx_inputs', related_query_name='tx_input', to='blocks.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='TxOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('n', models.IntegerField()),
                ('script_pub_key_asm', models.CharField(max_length=255)),
                ('script_pub_key_hex', models.CharField(max_length=255)),
                ('script_pub_key_type', models.CharField(max_length=255)),
                ('script_pub_key_req_sig', models.IntegerField(blank=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tx_outputs', related_query_name='tx_output', to='blocks.Transaction')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', related_query_name='address', to='blocks.TxOutput'),
        ),
    ]
