# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="txoutput",
            name="script_pub_key_asm",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="txoutput",
            name="script_pub_key_hex",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="txoutput",
            name="script_pub_key_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
