# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0002_auto_20160620_0741"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="hash",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="tx_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
