# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 20:19
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0004_auto_20160620_0844"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=6, max_digits=20)),
                ("call_back", models.URLField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="address",
            name="output",
        ),
        migrations.AddField(
            model_name="txoutput",
            name="addresses",
            field=models.ManyToManyField(
                related_name="output_addresses",
                related_query_name="output_address",
                to="blocks.Address",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="address",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="watchaddress",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watch_addresses",
                related_query_name="watch_address",
                to="blocks.Address",
            ),
        ),
    ]
