# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0005_auto_20160620_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='block',
        ),
        migrations.RemoveField(
            model_name='txinput',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='txoutput',
            name='transaction',
        ),
        migrations.AddField(
            model_name='block',
            name='transactions',
            field=models.ManyToManyField(related_name='transactions', related_query_name='transaction', to='blocks.Transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='inputs',
            field=models.ManyToManyField(related_name='inputs', related_query_name='input', to='blocks.TxInput'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='outputs',
            field=models.ManyToManyField(related_name='outputs', related_query_name='output', to='blocks.TxOutput'),
        ),
    ]
