# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0007_auto_20160621_1958"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchaddress",
            name="complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="address",
            name="address",
            field=models.CharField(max_length=610, unique=True),
        ),
        migrations.AlterField(
            model_name="block",
            name="bits",
            field=models.CharField(blank=True, max_length=610, null=True),
        ),
        migrations.AlterField(
            model_name="block",
            name="flags",
            field=models.CharField(blank=True, max_length=610, null=True),
        ),
        migrations.AlterField(
            model_name="block",
            name="hash",
            field=models.CharField(max_length=610, unique=True),
        ),
        migrations.AlterField(
            model_name="block",
            name="merkle_root",
            field=models.CharField(blank=True, max_length=610, null=True),
        ),
        migrations.AlterField(
            model_name="block",
            name="modifier",
            field=models.CharField(blank=True, max_length=610, null=True),
        ),
        migrations.AlterField(
            model_name="block",
            name="modifier_checksum",
            field=models.CharField(blank=True, max_length=610, null=True),
        ),
        migrations.AlterField(
            model_name="block",
            name="next_block_hash",
            field=models.CharField(blank=True, max_length=610, null=True),
        ),
        migrations.AlterField(
            model_name="block",
            name="previous_block_hash",
            field=models.CharField(blank=True, max_length=610, null=True),
        ),
        migrations.AlterField(
            model_name="block",
            name="proof_hash",
            field=models.CharField(blank=True, max_length=610, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="tx_id",
            field=models.CharField(max_length=610, unique=True),
        ),
        migrations.AlterField(
            model_name="txinput",
            name="coin_base",
            field=models.CharField(blank=True, max_length=610, null=True),
        ),
        migrations.AlterField(
            model_name="txinput",
            name="tx_id",
            field=models.CharField(blank=True, max_length=610, null=True),
        ),
        migrations.AlterField(
            model_name="txoutput",
            name="script_pub_key_asm",
            field=models.CharField(blank=True, max_length=610, null=True),
        ),
        migrations.AlterField(
            model_name="txoutput",
            name="script_pub_key_hex",
            field=models.CharField(blank=True, max_length=610, null=True),
        ),
        migrations.AlterField(
            model_name="txoutput",
            name="script_pub_key_type",
            field=models.CharField(blank=True, max_length=610, null=True),
        ),
        migrations.AlterField(
            model_name="watchaddress",
            name="call_back",
            field=models.URLField(max_length=610),
        ),
    ]
