# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0008_auto_20160622_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txoutput',
            name='script_pub_key_asm',
            field=models.TextField(blank=True, max_length=610, null=True),
        ),
        migrations.AlterField(
            model_name='txoutput',
            name='script_pub_key_hex',
            field=models.TextField(blank=True, max_length=610, null=True),
        ),
        migrations.AlterField(
            model_name='txoutput',
            name='script_pub_key_req_sig',
            field=models.TextField(blank=True, max_length=610, null=True),
        ),
        migrations.AlterField(
            model_name='txoutput',
            name='script_pub_key_type',
            field=models.TextField(blank=True, max_length=610, null=True),
        ),
    ]
