# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0009_auto_20160622_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='next_block',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='next',
                to='blocks.Block'
            ),
        ),
        migrations.AddField(
            model_name='block',
            name='previous_block',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='previous',
                to='blocks.Block'
            ),
            preserve_default=False,
        ),
        #migrations.RunPython(
        #    migrate_blocks,
        #),
    ]
