# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def migrate_blocks(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Block = apps.get_model("blocks", "Block")
    for block in Block.objects.all():
        try:
            block.previous_block = Block.objects.get(hash=block.previous_block_hash)
        except Block.DoesNotExist:
            pass

        try:
            block.next_block = Block.objects.get(hash=block.next_block_hash)
        except Block.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0009_auto_20160622_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='next_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blocks.Block'),
        ),
        migrations.AddField(
            model_name='block',
            name='previous_block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blocks.Block'),
            preserve_default=False,
        ),
        migrations.RunPython(
            migrate_blocks,
        ),
    ]
