# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-05 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0010_auto_20161103_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='next_block_hash',
        ),
        migrations.RemoveField(
            model_name='block',
            name='previous_block_hash',
        ),
        migrations.AlterField(
            model_name='block',
            name='next_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='blocks.Block'),
        ),
        migrations.AlterField(
            model_name='block',
            name='previous_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='blocks.Block'),
        ),
    ]
