# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-05 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0010_auto_20161103_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='next_block_hash',
        ),
        migrations.RemoveField(
            model_name='block',
            name='previous_block_hash',
        ),
        migrations.AddField(
            model_name='txoutput',
            name='is_unspent',
            field=models.BooleanField(default=True),
        ),
    ]
