# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0011_auto_20161105_2214"),
    ]

    operations = [
        migrations.AlterField(
            model_name="txoutput",
            name="addresses",
            field=models.ManyToManyField(
                related_name="output_addresses",
                related_query_name="tx_output",
                to="blocks.Address",
            ),
        ),
    ]
