# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-28 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0014_auto_20161127_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='txinput',
            name='script_sig_asm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='txinput',
            name='script_sig_hex',
            field=models.TextField(blank=True, null=True),
        ),
    ]
