# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-28 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0015_auto_20161128_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='unit',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
