# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-28 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0016_transaction_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="is_coin_base",
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="is_coin_stake",
            field=models.NullBooleanField(),
        ),
    ]
