# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0025_txinput_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='block',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', related_query_name='transaction', to='blocks.Block'),
        ),
        migrations.AlterField(
            model_name='txinput',
            name='previous_output',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_output', to='blocks.TxOutput'),
        ),
        migrations.AlterField(
            model_name='txinput',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', related_query_name='input', to='blocks.Transaction'),
        ),
        migrations.AlterField(
            model_name='txoutput',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', related_query_name='output', to='blocks.Transaction'),
        ),
    ]
