# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 10:32
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0026_auto_20170423_2205"),
    ]

    operations = [
        migrations.AlterField(
            model_name="txinput",
            name="previous_output",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_output",
                to="blocks.TxOutput",
            ),
        ),
    ]
