# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0027_auto_20170425_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='block',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', related_query_name='transaction', to='blocks.Block'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='index',
            field=models.BigIntegerField(blank=True),
        ),
    ]
