# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 07:46
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0028_auto_20170426_0737"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                related_query_name="transaction",
                to="blocks.Block",
            ),
        ),
        migrations.AlterField(
            model_name="transaction", name="index", field=models.BigIntegerField(),
        ),
    ]
