# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0030_auto_20170427_1018"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="txinput",
            unique_together=set([("transaction", "index")]),
        ),
    ]
