# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0030_auto_20170427_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='height',
            field=models.BigIntegerField(unique=True),
        ),
    ]
