# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0032_auto_20170430_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(db_index=True, max_length=610, unique=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='hash',
            field=models.CharField(db_index=True, max_length=610, unique=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='height',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_id',
            field=models.CharField(db_index=True, max_length=610, unique=True),
        ),
    ]
