# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 11:41
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0033_auto_20170504_0931"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                related_query_name="transaction",
                to="blocks.Block",
            ),
        ),
    ]
