# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0035_auto_20170504_1200"),
    ]

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit", models.CharField(max_length=255)),
                ("max_height", models.BigIntegerField()),
                ("money_supply", models.DecimalField(decimal_places=4, max_digits=16)),
                ("total_parked", models.DecimalField(decimal_places=4, max_digits=16)),
                ("connections", models.BigIntegerField()),
                ("difficulty", models.DecimalField(decimal_places=10, max_digits=16)),
                ("pay_tx_fee", models.DecimalField(decimal_places=4, max_digits=16)),
            ],
        ),
    ]
