# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 21:07
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0036_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="info",
            name="time_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
