# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0037_info_time_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="total_parked",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=16, null=True
            ),
        ),
    ]
