# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0040_auto_20170524_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txinput',
            name='previous_output',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input', to='blocks.TxOutput'),
        ),
        migrations.AlterField(
            model_name='txoutput',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outputs', related_query_name='output_address', to='blocks.Address'),
        ),
    ]
