# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0041_auto_20170528_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='unit',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='lock_time',
            field=models.IntegerField(default=0),
        ),
    ]
