# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0045_peer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orphan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.CharField(db_index=True, max_length=610, unique=True)),
                ("date_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
