# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 22:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0046_orphan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphan',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 28, 22, 2, 33, 972161, tzinfo=utc)),
        ),
    ]
