# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0048_auto_20170828_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='network_owned',
            field=models.BooleanField(default=False),
        ),
    ]
