# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-26 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0049_address_network_owned"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkFund",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=8, max_digits=25)),
            ],
        ),
    ]
