# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-26 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0050_networkfund"),
    ]

    operations = [
        migrations.AddField(
            model_name="networkfund",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
