# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-27 19:56
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daio", "0011_coin_decimal_places"),
        ("blocks", "0051_networkfund_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveParkRate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blocks.Block",
                    ),
                ),
                (
                    "coin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="daio.Coin",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="custodianvote",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blocks.Address",
            ),
        ),
        migrations.AddField(
            model_name="custodianvote",
            name="amount",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=25),
        ),
        migrations.AddField(
            model_name="custodianvote",
            name="block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blocks.Block",
            ),
        ),
        migrations.AddField(
            model_name="feesvote",
            name="block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blocks.Block",
            ),
        ),
        migrations.AddField(
            model_name="feesvote",
            name="coin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="daio.Coin",
            ),
        ),
        migrations.AddField(
            model_name="feesvote",
            name="fee",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25),
        ),
        migrations.AddField(
            model_name="motionvote",
            name="block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blocks.Block",
            ),
        ),
        migrations.AddField(
            model_name="motionvote",
            name="hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="parkrate", name="blocks", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="parkrate",
            name="rate",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25),
        ),
        migrations.AddField(
            model_name="parkratevote",
            name="block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blocks.Block",
            ),
        ),
        migrations.AddField(
            model_name="parkratevote",
            name="coin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="daio.Coin",
            ),
        ),
        migrations.AddField(
            model_name="parkratevote",
            name="rates",
            field=models.ManyToManyField(to="blocks.ParkRate"),
        ),
        migrations.AddField(
            model_name="activeparkrate",
            name="rates",
            field=models.ManyToManyField(to="blocks.ParkRate"),
        ),
    ]
