# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-29 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daio', '0011_coin_decimal_places'),
        ('blocks', '0053_networkfund_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daio.Coin'),
        ),
    ]
