# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-09 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0057_exchangebalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionvote',
            name='block_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='motionvote',
            name='sdd_percentage',
            field=models.FloatField(default=0),
        ),
    ]
