# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-29 15:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0059_block_amount_parked"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="park_rates",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="block",
            name="vote",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="block",
            name="amount_parked",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
