# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-11-20 07:50
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0062_auto_20180417_1435"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="time",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="info",
            name="max_height",
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="info",
            name="time_added",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="info",
            name="total_parked",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=4, max_digits=16, null=True
            ),
        ),
        migrations.AlterField(
            model_name="orphan",
            name="date_time",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="peer", name="height", field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="peer",
            name="last_receive",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="index",
            field=models.BigIntegerField(db_index=True, default=-1),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="time",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="txinput",
            name="index",
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="txoutput",
            name="index",
            field=models.IntegerField(db_index=True),
        ),
    ]
