# Generated by Django 2.2.16 on 2020-09-29 13:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0065_auto_20200927_2015"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_valid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="validity_errors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=150),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
