# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('daio_wallet', '0002_clienttoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttoken',
            name='token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255),
        ),
    ]
