# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('daio_wallet', '0003_auto_20160627_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
