# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daio_wallet', '0004_auto_20160627_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('to_address', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=8, max_digits=20)),
                ('tx_id', models.CharField(max_length=255)),
                ('complete', models.BooleanField()),
                ('callback', models.URLField()),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', related_query_name='transactions', to='daio_wallet.Wallet')),
            ],
        ),
    ]
