# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daio', '0008_coin_vout_n_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('order_amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('payment_price', models.DecimalField(decimal_places=4, max_digits=16)),
                ('order_price', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('api_base', models.URLField(max_length=500)),
                ('api_key', models.CharField(max_length=255)),
                ('api_secret', models.CharField(max_length=255)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', related_query_name='exchange', to='daio.Chain')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('order_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=255)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=16)),
                ('total', models.DecimalField(decimal_places=4, max_digits=16)),
                ('payment_price', models.DecimalField(decimal_places=4, max_digits=16)),
                ('order_price', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('payment_currency', models.CharField(max_length=255)),
                ('order_currency', models.CharField(max_length=255)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', related_query_name='pair', to='charts.Exchange')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', related_query_name='order', to='charts.Pair'),
        ),
        migrations.AddField(
            model_name='balance',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', related_query_name='balance', to='charts.Pair'),
        ),
    ]
