# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='balance',
            name='order_amount',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='order_price',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='payment_price',
        ),
        migrations.RemoveField(
            model_name='pair',
            name='order_currency',
        ),
        migrations.RemoveField(
            model_name='pair',
            name='payment_currency',
        ),
        migrations.AddField(
            model_name='balance',
            name='base_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='quote_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_price',
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('order_id', 'pair')]),
        ),
        migrations.AddField(
            model_name='pair',
            name='base_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_currencies', related_query_name='base_currency', to='charts.Currency'),
        ),
        migrations.AddField(
            model_name='pair',
            name='quote_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_currencies', related_query_name='quote_currency', to='charts.Currency'),
        ),
    ]
