# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_auto_20170619_1842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Trade',
        ),
    ]
