# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_auto_20170619_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ('-date_time',)},
        ),
        migrations.AlterField(
            model_name='trade',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=26, null=True),
        ),
    ]
