# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0006_currency_get_usd_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('usd_value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', related_query_name='value', to='charts.Currency')),
            ],
        ),
    ]
