# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0012_auto_20170622_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('trade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='charts.Trade')),
                ('closed', models.BooleanField(default=False)),
                ('remaining', models.DecimalField(decimal_places=10, max_digits=26)),
            ],
            bases=('charts.trade',),
        ),
    ]
