# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0013_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='remaining',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=26, null=True),
        ),
    ]
