# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0014_auto_20170625_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='closed',
        ),
        migrations.AddField(
            model_name='order',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
