# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0015_auto_20170625_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeTx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_tx_id', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('tx_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=10, max_digits=26, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=10, max_digits=26, null=True)),
                ('complete', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('exchangetx_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='charts.ExchangeTx')),
                ('tx_type', models.CharField(choices=[('WITHDRAWAL', 'Withdrawal'), ('DEPOSIT', 'Deposit')], default='DEPOSIT', max_length=255)),
            ],
            bases=('charts.exchangetx',),
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('exchangetx_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='charts.ExchangeTx')),
                ('tx_type', models.CharField(choices=[('WITHDRAWAL', 'Withdrawal'), ('DEPOSIT', 'Deposit')], default='WITHDRAWAL', max_length=255)),
            ],
            bases=('charts.exchangetx',),
        ),
        migrations.AddField(
            model_name='exchangetx',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_tx', related_query_name='exchange_txs', to='charts.Currency'),
        ),
    ]
