# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0017_exchangetx_exchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangetx',
            name='exchange',
        ),
        migrations.AddField(
            model_name='exchangetx',
            name='pair',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_tx', related_query_name='exchange_txs', to='charts.Pair'),
            preserve_default=False,
        ),
    ]
