# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0018_auto_20170627_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
