# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0020_watchedaddress_watchedaddressbalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchedaddress',
            name='balance_service',
        ),
        migrations.AddField(
            model_name='watchedaddress',
            name='currency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='charts.Currency'),
            preserve_default=False,
        ),
    ]
