# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0022_currency_decimal_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_created=True)),
                ('reply_channel', models.CharField(max_length=255, unique=True)),
                ('tx_browser_running', models.BooleanField(default=False)),
            ],
        ),
    ]
