# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0048_auto_20170828_2203'),
        ('charts', '0024_auto_20170925_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocket',
            name='blocks',
            field=models.ManyToManyField(to='blocks.Block'),
        ),
    ]
