# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('alert_operator', models.CharField(choices=[('EQUALS', '='), ('LESS_THAN', '<'), ('GREATER_THAN', '>')], max_length=255)),
                ('alert_value', models.DecimalField(decimal_places=8, max_digits=50)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
