# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0021_auto_20170710_1519'),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceAlert',
            fields=[
                ('alert_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alerts.Alert')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.Currency')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.Exchange')),
            ],
            bases=('alerts.alert',),
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('DISCOURSE', 'Discourse'), ('GITTER', 'Gitter'), ('EMAIL', 'Email')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.URLField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('api_user_name', models.CharField(max_length=255)),
                ('target_channel', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='alert',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='object_id',
        ),
    ]
