# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_auto_20170731_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='provider',
            field=models.ManyToManyField(to='alerts.Connector'),
        ),
    ]
