# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='provider',
            new_name='providers',
        ),
    ]
