# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0021_auto_20170710_1519'),
        ('alerts', '0004_auto_20170801_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancealert',
            name='exchange',
        ),
        migrations.AddField(
            model_name='balancealert',
            name='pair',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='charts.Pair'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balancealert',
            name='currency',
            field=models.CharField(choices=[('BASE', 'Base'), ('QUOTE', 'quote')], max_length=10),
        ),
    ]
