# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_auto_20170801_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancealert',
            name='currency',
            field=models.CharField(choices=[('BASE', 'Base'), ('QUOTE', 'Quote')], max_length=10),
        ),
    ]
