# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daio', '0004_auto_20170504_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='rpc_port',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chain',
            name='rpc_port',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
