# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daio', '0005_auto_20170504_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='magic_byte',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
