# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daio", "0006_coin_magic_byte"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coin",
            options={"ordering": ["index"]},
        ),
        migrations.AddField(
            model_name="coin",
            name="index",
            field=models.IntegerField(default=0),
        ),
    ]
