# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daio", "0007_auto_20170508_1926"),
    ]

    operations = [
        migrations.AddField(
            model_name="coin",
            name="vout_n_value",
            field=models.CharField(default="ffffffff", max_length=255),
        ),
    ]
