# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daio", "0008_coin_vout_n_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="logo",
            field=models.FileField(
                default="test", max_length=255, upload_to="chain/logo/"
            ),
            preserve_default=False,
        ),
    ]
