# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daio", "0009_chain_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chain",
            name="logo",
            field=models.FileField(max_length=255, upload_to="logo/"),
        ),
    ]
