# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daio', '0010_auto_20170714_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='decimal_places',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
