# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-11-20 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daio', '0011_coin_decimal_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='index',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
