# Generated by Django 2.2.16 on 2020-09-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daio', '0012_auto_20191120_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='rpc_active',
            field=models.BooleanField(default=True),
        ),
    ]
