name: test_deploy

on:
  push:
    branches:
      - master

jobs:
  lint_test_deploy:
    name: lint then test then deploy
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install dependencies
        run: |
          pipenv sync --dev

      - name: Run pre-commit
        run: |
          pipenv run pre-commit run -a --verbose

      - name: run tests
        run: |
          pipenv run pytest

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/daio/crypto-daio
            git pull origin master
            sudo supervisorctl restart daio:*
