name: test_deploy

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: lint all code
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install dependencies
        run: |
          pipenv sync --dev

      - name: Analysing the code with pylint
        run: |
          pipenv run pre-commit --all
